language: python
rmv:
 - "3.5"

install: 
 - pip install python-coveralls
 - pip install coveralls
 - pip install coverage
 - pip install pytest-cov
 - pip install pyYaml
 - pip install colorama
script:
 - make test
 - pytest --cov

after_success:
 - coveralls
